

// FAKE DATA
export const books = [
    {
      id: 1,
      title: "Crack the Coding Interview",
                url: "https://m.media-amazon.com/images/I/61mIq2iJUXL.jpg",
      originalPrice: 49.95,
      salePrice: 14.95,
      rating: 4.5,
    },
    {
      id: 2,
      title: "Atomic Habits",
      url: "https://m.media-amazon.com/images/I/81ANaVZk5LL.jpg",
      originalPrice: 39,
      salePrice: null,
      rating: 5,
    },
    {
      id: 3,
      title: "Deep Work",
      url: "https://m.media-amazon.com/images/I/81JJ7fyyKyS.jpg",
      originalPrice: 29,
      salePrice: 12,
      rating: 5,
    },
    {
      id: 4,
      title: "The 10X Rule",
      url: "https://m.media-amazon.com/images/I/71hjq42hvGL._AC_UF1000,1000_QL80_.jpg",
      originalPrice: 44,
      salePrice: 19,
      rating: 5,
    },
    {
      id: 5,
      title: "Be Obsessed Or Be Average",
      url: "https://m.media-amazon.com/images/I/81iRBQRrzVL.jpg",
      originalPrice: 32,
      salePrice: 17,
      rating: 4,
    },
    {
      id: 6,
      title: "Rich Dad Poor Dad",
      url: "https://m.media-amazon.com/images/I/81bsw6fnUiL._AC_UF1000,1000_QL80_.jpg",
      originalPrice: 70,
      salePrice: 12.5,
      rating: 5,
    },
    {
      id: 7,
      title: "Cashflow Quadrant",
      url: "https://m.media-amazon.com/images/I/71+SWQ6xj1L.jpg",
      originalPrice: 11,
      salePrice: 10,
      rating: 4,
    },
    {
      id: 8,
      title: "48 Laws of Power",
      url: "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UF1000,1000_QL80_.jpg",
      originalPrice: 38,
      salePrice: 17.95,
      rating: 4.5,
    },
    {
      id: 9,
      title: "The 5 Second Rule",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-R6ci9xyJgAXDI7Hxh-tM2zSYLY1__ECWsg&s",
      originalPrice: 35,
      salePrice: null,
      rating: 4,
    },
    {
      id: 10,
      title: "Your Next Five Moves",
      url: "https://m.media-amazon.com/images/I/71ah+6D5ahL.jpg",
      originalPrice: 40,
      salePrice: null,
      rating: 4,
    },
    {
      id: 11,
      title: "Mastery",
      url: "https://m.media-amazon.com/images/I/61M2Zzw9FyL.jpg",
      originalPrice: 30,
      salePrice: null,
      rating: 4.5,
    },
  ];

